version: '3.6'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: recipehub
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/functions.sql:/docker-entrypoint-initdb.d/02-functions.sql
      - ./database/triggers.sql:/docker-entrypoint-initdb.d/03-triggers.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/04-seed.sql
    ports:
      - "5432:5432"

  graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/recipehub
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/recipehub
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      ## JWT secret for authentication
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"your-256-bit-secret-key-here-make-it-long-and-random"}'
      ## Actions base URL
      HASURA_GRAPHQL_ACTIONS_BASE_URL: http://golang-api:8000
    depends_on:
      - postgres

  golang-api:
    build:
      context: ./golang-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/recipehub
      JWT_SECRET: your-256-bit-secret-key-here-make-it-long-and-random
      HASURA_ADMIN_SECRET: myadminsecretkey
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      CHAPA_SECRET_KEY: your-chapa-secret-key
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

volumes:
  db_data:
